name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
      - run: curl -L  https://github.com/streamingfast/substreams/releases/download/v1.1.20/substreams_linux_x86_64.tar.gz > substreams.tar.gz
      - run: tar xf substreams.tar.gz
      - run: sudo ln substreams /usr/bin
      - run: rustup target add wasm32-unknown-unknown
      - run: make protogen
      - run: make build
      #- run: substreams pack